using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;

namespace VirtualPetsAmok
{
    public class Animations
    {
         public void Title()
        {
            Console.ForegroundColor = ConsoleColor.Magenta;
            Console.WriteLine(@"                                                 
 _____  _____  _____  _____  _____  _____  __    
|  |  ||     || __  ||_   _||  |  ||  _  ||  |   
|  |  ||-   -||    -|  | |  |  |  ||     ||  |__ 
 \___/ |_____||__|__|  |_|  |_____||__|__||_____|
                                                 ");
            Console.WriteLine(@"                                                          
 _____  _____  _____  _____    _____  _____  _____  _____ 
|  _  ||   __||_   _||   __|  |  _  ||     ||     ||  |  |
|   __||   __|  | |  |__   |  |     || | | ||  |  ||    -|
|__|   |_____|  |_|  |_____|  |__|__||_|_|_||_____||__|__|
                                                          ");
            Console.ForegroundColor = ConsoleColor.White;
        }


        public void Lights()
        {
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            light();
            light2();
            light3();
            light4();
            light5();
            light6();
            light7();
            light8();
            light9();
            light10();
            light11();
            light12();
            light13();
            light14();
            light15();
            light16();
            light17();
            light18();
            light19();
            light20();
            light21();
            light22();
            light23();
            light24();
            light25();
            light26();
            light27();
            light28();
            light29();
            Console.ForegroundColor = ConsoleColor.White;
        }


        static void light()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
    ..........                      ..........
     .........                       ..........
      ........                        ..........
       .......                          .........
        ......            We Can Code IT  ........
         .....           ================   .......
          ....              PRODUCTION         .....
           ...                                    ...
            ..                                      ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");

        }

        static void light2()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
     ..........                      ..........
      .........                       ..........
       ........                        ..........
        .......                          .........
        ......            We Can Code IT  ........
         .....           ================   .......
          ....              PRODUCTION         .....
           ...                                    ...
            ..                                      ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");

        }

        static void light3()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
      ..........                      ..........
       .........                       ..........
       ........                         ..........
         .......                          .........
         ......           We Can Code IT   ........
          .....          ================    .......
           ....             PRODUCTION          .....
            ...                                    ...
            ..                                      ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");
        }

        static void light4()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
       ..........                      ..........
       .........                        ..........
        ........                         ..........
         .......                          .........
          ......          We Can Code IT    ........
           .....         ================    .......
           ....             PRODUCTION          .....
            ...                                    ...
            ..                                      ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");
        }

        static void light5()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
         ..........                      ..........
        .........                        ..........
         ........                         ..........
          .......                          .........
           ......         We Can Code IT     ........
            .....        ================     .......
            ....            PRODUCTION          .....
            ...                                    ...
            ..                                      ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");
        }

        static void light6()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
          ..........                       ..........
         .........                         ..........
          ........                          ..........
           .......                           .........
           .......        We Can Code IT      ........
            .....        ================       .......
           .....            PRODUCTION           .....
            ...                                    ...
            ..                                      ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");
        }

        static void light7()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
           ..........                        ..........
           .........                          ..........
           ........                           ..........
            .......                            .........
            ......        We Can Code IT       ........
             .....       ================        .......
            ....            PRODUCTION           .....
             ...                                    ...
            ..                                      ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");
        }

        static void light8()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
            ..........                        ..........
            .........                          ..........
            ........                           ..........
             .......                            .........
             ......       We Can Code IT         ........
             .....       ================        .......
             ....           PRODUCTION            .....
             ...                                    ...
            ..                                      ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");
        }

        static void light9()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
             ..........                        ..........
             .........                          ..........
             ........                           ..........
              .......                            .........
             ......       We Can Code IT         ........
              .....      ================        .......
             ....           PRODUCTION            .....
             ...                                    ...
            ..                                      ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");
        }

        static void light10()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
              ..........                        ..........
              .........                          ..........
              ........                            ..........
              .......                            .........
              ......      We Can Code IT         ........
              .....      ================         .......
              ....          PRODUCTION            .....
             ...                                    ...
            ..                                      ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");
        }

        static void light11()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
               ..........                          ..........
               .........                          ..........
              ........                            ..........
               .......                            .........
               ......     We Can Code IT          ........
              .....      ================          .......
              ....          PRODUCTION             .....
             ...                                    ...
            ..                                       ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");
        }

        static void light12()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
                ..........                          ..........
                .........                          ..........
               ........                            ..........
               .......                              .........
              .......     We Can Code IT           ........
              ......     ================          .......
              ....          PRODUCTION              .....
             ...                                    ...
            ..                                       ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");
        }

        static void light13()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
                 ..........                          ..........
                 .........                          ..........
                ........                             ..........
               .......                              .........
               .......    We Can Code IT             ........
              ......     ================           .......
              ....          PRODUCTION               .....
             ...                                     ...
            ..                                       ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");
        }

        static void light14()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
                  ..........                          ..........
                  .........                          ..........
                 ........                             ..........
                .......                               .........
               .......    We Can Code IT             ........
               ......    ================            .......
              ....          PRODUCTION                .....
             ...                                     ...
            ..                                       ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");
        }

        static void light15()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
                 ..........                            ..........
                  .........                           ..........
                ........                               ..........
                .......                               .........
                ......    We Can Code IT              ........
               ......    ================             .......
               ....         PRODUCTION                .....
             ...                                     ...
            ..                                       ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");

        }

        static void light16()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
                ..........                              ..........
                 .........                              ..........
                ........                               ..........
               .......                                 .........
               ......     We Can Code IT               ........
               ......    ================              .......
              ....          PRODUCTION                .....
             ...                                     ...
            ..                                       ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");

        }

        static void light17()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
               ..........                                ..........
                .........                                ..........
               ........                                ..........
               .......                                  .........
              ......      We Can Code IT               ........
               ......    ================               .......
             ....           PRODUCTION                .....
             ...                                      ...
            ..                                       ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");

        }

        static void light18()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
              ..........                                  ..........
               .........                                  ..........
               ........                                  ..........
              .......                                    .........
              ......      We Can Code IT                ........
              ......     ================               .......
             ....           PRODUCTION                .....
            ...                                       ...
            ..                                       ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");

        }

        static void light19()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
             ..........                                  ..........
              .........                                 ..........
              ........                                  ..........
             .......                                    .........
             ......       We Can Code IT               ........
             ......      ================              .......
             ....           PRODUCTION                .....
            ...                                      ...
            ..                                       ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");

        }

        static void light20()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
            ..........                                 ..........
             .........                                 ..........
             ........                                  ..........
            .......                                   .........
             ......       We Can Code IT               ........
            ......       ================             .......
             ....           PRODUCTION               .....
            ...                                      ...
            ..                                       ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");

        }

        static void light21()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
           ..........                                ..........
            .........                                 ..........
            ........                                 ..........
           .......                                    .........
            ......        We Can Code IT             ........
            ......       ================             .......
            ....            PRODUCTION              .....
            ...                                      ...
            ..                                       ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");

        }

        static void light22()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
          ..........                                ..........
           .........                               ..........
           ........                                 ..........
          .......                                    .........
           ......         We Can Code IT            ........
           ......        ================           .......
           ....             PRODUCTION              .....
            ...                                      ...
            ..                                       ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");

        }

        static void light23()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
         ..........                                ..........
          .........                               ..........
          ........                                 ..........
          .......                                  .........
           ......         We Can Code IT            ........
          ......         ================           .......
           ....             PRODUCTION              .....
            ...                                      ...
            ..                                       ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");

        }

        static void light24()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
        ..........                                ..........
         .........                               ..........
         ........                                 ..........
          .......                                  .........
          ......          We Can Code IT           ........
          ......         ================          .......
           ....             PRODUCTION              .....
            ...                                     ...
            ..                                       ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");

        }

        static void light25()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
       ..........                               ..........
        .........                               ..........
        ........                                ..........
         .......                                 .........
          ......          We Can Code IT           ........
          ......         ================         .......
           ....             PRODUCTION            .....
           ...                                     ...
            ..                                       ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");

        }

        static void light26()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
      ..........                            ..........
       .........                              ..........
       ........                               ..........
        .......                                 .........
         ......           We Can Code IT        ........
          ......         ================       .......
          ....              PRODUCTION            .....
           ...                                     ...
            ..                                       ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");

        }

        static void light27()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
     ..........                           ..........
       .........                            ..........
      ........                              ..........
        .......                               .........
         ......           We Can Code IT        ........
        ......           ================       .......
          ....              PRODUCTION            .....
           ...                                     ...
            ..                                       ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");

        }

        static void light28()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
    ..........                          ..........
      .........                          ..........
      ........                             ..........
       .......                              .........
        ......            We Can Code IT      ........
         .....           ================     .......
          ....              PRODUCTION          .....
           ...                                     ...
            ..                                       ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");

        }

        static void light29()
        {
            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"
    ..........                        ..........
     .........                          ..........
      ........                            ..........
       .......                             .........
        ......            We Can Code IT    ........
         .....           ================     .......
          ....              PRODUCTION          .....
           ...                                     ...
            ..                                       ..
            ==                                       ==
          __ll__                                   __ll__
         |      |                                 |      |
     ____|______|_____                        ____|______|____

");

        }

    }
}

